server:
  port: 8080

spring:
  application:
    name: shared-checklist
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yml

# Disable unnecessary Spring Boot features for performance  
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health

logging:
  level:
    com.jcw.checklist: INFO
    org.springframework.security: WARN
    org.hibernate: WARN