spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checklistdb
    username: youruser
    password: yourpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect